// Generated by CoffeeScript 1.9.1
(function() {
  var projectPartners;

  projectPartners = function(n) {
    return n * (n - 1) / 2;
  };

}).call(this);

//# sourceMappingURL=projectPartners.js.map
